---
language: python
python:
  - "3.6"
  - "3.7"
services:
  - mongodb
install:
  - pip install -r requirements.txt
script:
  - pylint *
  - coverage run --source=tests/ -m pytest tests
  - coverage report --fail-under=90